sudo: required
services:
  - docker

before_install:
  - docker build -t meatball117/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true meatball117/docker-react npm run test -- --coverage 
